---
title: "Tidy data"
output: github_document
---

```{r setup}
library(tidyr)
library(tidyverse)
options(tibble.print_min = 5)
```

## `pivot_longer`

Load the PULSE data
```{r}
pulse_df = 
  haven::read_sas("C:/Users/prize/Dropbox/Prize/CUIMC_MPH2YR/Fall 2025/Data Science I/Week 2/data_manipulation/tidy data/data/public_pulse_data.sas7bdat") |> 
  janitor::clean_names()

pulse_df
```

Wide format to long format...


```{r}
library(tidyr)

pulse_tidy_df = 
  pivot_longer(
    pulse_df, 
    bdi_score_bl:bdi_score_12m,
    names_to = "visit", 
    values_to = "bdi")

pulse_tidy_df
```

names_to -- create a new variable to put bdi_score_bl

clean more prefix...
```{r}
pulse_tidy_df = 
  pivot_longer(
    pulse_df, 
    bdi_score_bl:bdi_score_12m,
    names_to = "visit", 
    names_prefix = "bdi_score_",
    values_to = "bdi")

pulse_tidy_df
```

Rewrite, combine, and extend (to add a mutate)
```{r}
library(dplyr)

pulse_data = 
  haven::read_sas("C:/Users/prize/Dropbox/Prize/CUIMC_MPH2YR/Fall 2025/Data Science I/Week 2/data_manipulation/tidy data/data/public_pulse_data.sas7bdat") |>
  janitor::clean_names() |>
  pivot_longer(
    bdi_score_bl:bdi_score_12m,
    names_to = "visit",
    names_prefix = "bdi_score_",
    values_to = "bdi"
  ) |>
  relocate(id,visit) |> 
  mutate(visit = recode(visit, "bl" = "00m"))

```

## `pivot_wider`

Make up some data!

```{r}
analysis_result = 
  tibble(
    group = c("treatment", "treament", "placebo", "placebo"),
    time = c("pre", "post", "pre", "post"),
    mean = c(4, 8, 3.5, 4)
  )

analysis_result
 
pivot_wider(
    analysis_result,
    names_from = "time",
    values_from = "mean"
  )
```

## Binding rows
Using the LotR data.
First step: import each table.

```{r}
fellowship_ring = 
  readxl::read_excel("C:/Users/prize/Dropbox/Prize/CUIMC_MPH2YR/Fall 2025/Data Science I/Week 2/data_manipulation/tidy data/data/LotR_Words.xlsx", range = "B3:D6") |>
  mutate(movie = "fellowship_ring")


two_towers = 
  readxl::read_excel("C:/Users/prize/Dropbox/Prize/CUIMC_MPH2YR/Fall 2025/Data Science I/Week 2/data_manipulation/tidy data/data/LotR_Words.xlsx", range = "F3:h6") |>
  mutate(movie = "two_towers")


Return_king = 
  readxl::read_excel("C:/Users/prize/Dropbox/Prize/CUIMC_MPH2YR/Fall 2025/Data Science I/Week 2/data_manipulation/tidy data/data/LotR_Words.xlsx", range = "J3:L6") |>
  mutate(movie = "return_king")
```

Bind all the rows together
```{r}
lotr_tidy =
  bind_rows(fellowship_ring, two_towers, Return_king) |> 
  janitor::clean_names() |> 
  relocate(movie) |> 
  pivot_longer(
    female:male,
    names_to = "gender",
    values_to = "words"
  )

lotr_tidy
```





